### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by divamgupta** [imatlab/imatlab#21]
I am trying to install imatlab in ubuntu 14.04 with R2016b. But I encountered the following error:

```
python3  -mimatlab install
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.4/dist-packages/imatlab/__main__.py", line 3, in <module>
    from ._kernel import MatlabKernel
  File "/usr/local/lib/python3.4/dist-packages/imatlab/_kernel.py", line 65
    **({} if success else {"error": "true"})})
     ^
SyntaxError: invalid syntax


```

**Comment by anntzer** [comment]
https://github.com/imatlab/imatlab#a-jupyter-kernel-for-matlab says py3.5+.  You have py3.4.
