### ISSUE TITLE
Does not work with python 3.6

### ISSUE THREAD

**Issue by josephcslater** [imatlab/imatlab#22]
Unfortunately installation fails under python 3.6. I hacked the matlab engine to allow 3.6 to be "believed supported", but then imatlab had a fit (below). 

I'm at a loss. 

-----------------------------------------------
Traceback (most recent call last):
  File "/Users/jslater/anaconda/lib/python3.6/site-packages/matlab/engine/__init__.py", line 42, in <module>
    pythonengine = importlib.import_module("matlabengineforpython"+_PYTHONVERSION)
  File "/Users/jslater/anaconda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'matlabengineforpython3_6'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jslater/anaconda/lib/python3.6/site-packages/matlab/engine/__init__.py", line 58, in <module>
    pythonengine = importlib.import_module("matlabengineforpython"+_PYTHONVERSION)
  File "/Users/jslater/anaconda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'matlabengineforpython3_6'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jslater/anaconda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/jslater/anaconda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jslater/anaconda/lib/python3.6/site-packages/imatlab/__main__.py", line 3, in <module>
    from ._kernel import MatlabKernel
  File "/Users/jslater/anaconda/lib/python3.6/site-packages/imatlab/_kernel.py", line 17, in <module>
    import matlab.engine
  File "/Users/jslater/anaconda/lib/python3.6/site-packages/matlab/engine/__init__.py", line 61, in <module>
    'MathWorks Technical Support for assistance: %s' % e)
OSError: Please reinstall MATLAB Engine for Python or contact MathWorks Technical Support for assistance: No module named 'matlabengineforpython3_6'

**Comment by anntzer** [comment]
If the engine does not support Py3.6 then the kernel will not support it either.  I've clarified this in the README.
Some tricks are possible to work around this limitation (see e.g. https://pastebin.com/Ti6FyDTa) but I will not provide support for them.
