### ISSUE TITLE
Error when shutting down kernel.

### ISSUE THREAD

**Issue by Amartel1986** [imatlab/imatlab#32]
I send `SHUTDOWN_REQUEST` message and instead of `SHUTDOWN_REPLY` receive error.

Messages:

> SEND: {"header":{"username":"","session":"f67e350b-1f2e-49bb-a23d-bf6d538923fd","date":"2017-11-13T12:33:32.040Z","version":"5.1","msg_id":"6c1c2315-a814-4299-af24-63215ea34d78","msg_type":"shutdown_request"},"channel":"shell","metadata":null,"content":{"restart":false},"msg_type":"shutdown_request","msg_id":"6c1c2315-a814-4299-af24-63215ea34d78","parent_header":null}

> RECEIVE: {"content": {"execution_state": "busy"}, "header": {"session": "14b81d0d-b366675aec0a85b85bf14ed2", "version": "5.2", "msg_type": "status", "date": "2017-11-13T12:33:32.043253Z", "username": "username", "msg_id": "d5f33811-bc0ed3fe4d1e28378f4b39f2"}, "channel": "iopub", "msg_type": "status", "metadata": {}, "msg_id": "d5f33811-bc0ed3fe4d1e28378f4b39f2", "buffers": [], "parent_header": {"session": "f67e350b-1f2e-49bb-a23d-bf6d538923fd", "version": "5.1", "msg_type": "shutdown_request", "date": "2017-11-13T12:33:32.040000Z", "username": "", "msg_id": "6c1c2315-a814-4299-af24-63215ea34d78"}}

> RECEIVE: {"content": {"text": "Error using exit\nToo many output arguments.\n\n", "name": "stderr"}, "header": {"session": "14b81d0d-b366675aec0a85b85bf14ed2", "version": "5.2", "msg_type": "stream", "date": "2017-11-13T12:33:32.046337Z", "username": "username", "msg_id": "f5d28a1f-df01395103ee2314a59bb5fc"}, "channel": "iopub", "msg_type": "stream", "metadata": {}, "msg_id": "f5d28a1f-df01395103ee2314a59bb5fc", "buffers": [], "parent_header": {"session": "f67e350b-1f2e-49bb-a23d-bf6d538923fd", "version": "5.1", "msg_type": "shutdown_request", "date": "2017-11-13T12:33:32.040000Z", "username": "", "msg_id": "6c1c2315-a814-4299-af24-63215ea34d78"}}

> RECEIVE: {"content": {"text": "[IPKernelApp] ERROR | Exception in message handler:\nTraceback (most recent call last):\n  File \"/opt/conda/lib/python3.5/site-packages/ipykernel/kernelbase.py\", line 235, in dispatch_shell\n    handler(stream, idents, msg)\n  File \"/opt/conda/lib/python3.5/site-packages/ipykernel/kernelbase.py\", line 528, in shutdown_request\n    content = self.do_shutdown(parent['content']['restart'])\n  File \"/opt/conda/lib/python3.5/site-packages/imatlab/kernel.py\", line 345, in do_shutdown\n    self.call(\"exit\")\n  File \"/opt/conda/lib/python3.5/site-packages/imatlab/_kernel.py\", line 91, in _call\n    return self._engine.builtin(args, *kwargs)\n  File \"/opt/conda/lib/python3.5/site-packages/matlab/engine/matlabengine.py\", line 84, in __call\n    _stderr, feval=True).result()\n  File \"/opt/conda/lib/python3.5/site-packages/matlab/engine/futureresult.py\", line 68, in result\n    return self.__future.result(timeout)\n  File \"/opt/conda/lib/python3.5/site-packages/matlab/engine/fevalfuture.py\", line 82, in result\n    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)\nmatlab.engine.MatlabExecutionError: Too many output arguments.\n\n", "name": "stderr"}, "header": {"session": "14b81d0d-b366675aec0a85b85bf14ed2", "version": "5.2", "msg_type": "stream", "date": "2017-11-13T12:33:32.047840Z", "username": "username", "msg_id": "d2e9e4e4-a5f249a152f000d9a970e8d8"}, "channel": "iopub", "msg_type": "stream", "metadata": {}, "msg_id": "d2e9e4e4-a5f249a152f000d9a970e8d8", "buffers": [], "parent_header": {"session": "f67e350b-1f2e-49bb-a23d-bf6d538923fd", "version": "5.1", "msg_type": "shutdown_request", "date": "2017-11-13T12:33:32.040000Z", "username": "", "msg_id": "6c1c2315-a814-4299-af24-63215ea34d78"}}

**Comment by anntzer** [comment]
Should be fixed as of master.  Feel free to request a reopen if not.

**Comment by Amartel1986** [comment]
Unfortunately, the problem seems to remain:

> SEND: {"header":{"username":"","session":"14802e2d-5f9f-45f5-a15e-7bbf8bb99424","date":"2017-11-16T13:18:35.785Z","version":"5.1","msg_id":"a562f885-a267-4e7c-bfe8-bd4abc5bac7f","msg_type":"shutdown_request"},"channel":"shell","metadata":null,"content":{"restart":false},"msg_type":"shutdown_request","msg_id":"a562f885-a267-4e7c-bfe8-bd4abc5bac7f","parent_header":null}

> RECEIVE: {"buffers": [], "header": {"msg_id": "4800775a-4a3066c819d91b380926c81d", "date": "2017-11-16T13:18:35.788478Z", "username": "username", "version": "5.2", "session": "d71bccd8-ae3ea1e8467f5714f65a5a1d", "msg_type": "status"}, "channel": "iopub", "metadata": {}, "parent_header": {"msg_id": "a562f885-a267-4e7c-bfe8-bd4abc5bac7f", "date": "2017-11-16T13:18:35.785000Z", "username": "", "version": "5.1", "session": "14802e2d-5f9f-45f5-a15e-7bbf8bb99424", "msg_type": "shutdown_request"}, "msg_id": "4800775a-4a3066c819d91b380926c81d", "content": {"execution_state": "busy"}, "msg_type": "status"}

> RECEIVE: {"buffers": [], "header": {"msg_id": "a6eb28c0-0dcaa201812bf9e2f7fbce45", "date": "2017-11-16T13:18:35.792497Z", "username": "username", "version": "5.2", "session": "d71bccd8-ae3ea1e8467f5714f65a5a1d", "msg_type": "stream"}, "channel": "iopub", "metadata": {}, "parent_header": {"msg_id": "a562f885-a267-4e7c-bfe8-bd4abc5bac7f", "date": "2017-11-16T13:18:35.785000Z", "username": "", "version": "5.1", "session": "14802e2d-5f9f-45f5-a15e-7bbf8bb99424", "msg_type": "shutdown_request"}, "msg_id": "a6eb28c0-0dcaa201812bf9e2f7fbce45", "content": {"name": "stderr", "text": "Error using exit\nToo many output arguments.\n\n"}, "msg_type": "stream"}

> RECEIVE: {"buffers": [], "header": {"msg_id": "5378d50b-7d73fb425cb0dd45761305c0", "date": "2017-11-16T13:18:35.794408Z", "username": "username", "version": "5.2", "session": "d71bccd8-ae3ea1e8467f5714f65a5a1d", "msg_type": "stream"}, "channel": "iopub", "metadata": {}, "parent_header": {"msg_id": "a562f885-a267-4e7c-bfe8-bd4abc5bac7f", "date": "2017-11-16T13:18:35.785000Z", "username": "", "version": "5.1", "session": "14802e2d-5f9f-45f5-a15e-7bbf8bb99424", "msg_type": "shutdown_request"}, "msg_id": "5378d50b-7d73fb425cb0dd45761305c0", "content": {"name": "stderr", "text": "[IPKernelApp] ERROR | Exception in message handler:\nTraceback (most recent call last):\n  File \"/opt/conda/lib/python3.5/site-packages/ipykernel/kernelbase.py\", line 235, in dispatch_shell\n    handler(stream, idents, msg)\n  File \"/opt/conda/lib/python3.5/site-packages/ipykernel/kernelbase.py\", line 528, in shutdown_request\n    content = self.do_shutdown(parent['content']['restart'])\n  File \"/opt/conda/lib/python3.5/site-packages/imatlab/_kernel.py\", line 345, in do_shutdown\n    self._call(\"exit\")\n  File \"/opt/conda/lib/python3.5/site-packages/imatlab/_kernel.py\", line 91, in _call\n    return self._engine.builtin(*args, **kwargs)\n  File \"/opt/conda/lib/python3.5/site-packages/matlab/engine/matlabengine.py\", line 84, in __call__\n    _stderr, feval=True).result()\n  File \"/opt/conda/lib/python3.5/site-packages/matlab/engine/futureresult.py\", line 68, in result\n    return self.__future.result(timeout)\n  File \"/opt/conda/lib/python3.5/site-packages/matlab/engine/fevalfuture.py\", line 82, in result\n    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)\nmatlab.engine.MatlabExecutionError: Too many output arguments.\n\n"}, "msg_type": "stream"}

**Comment by Amartel1986** [comment]
Fortunately, I've found a workaround. Sending `DELETE` to `/api/kernels/{kernelId}` does exactly what I need.

**Comment by anntzer** [comment]
Can you provide a way to reproduce the issue?

**Comment by Amartel1986** [comment]
Launch jupyter with your kernel on port 8254 (or change it in script, provided). I do it like this:

```
docker run --rm -p 8254:8888 <DOCKER_IMAGE> /usr/local/bin/start.sh jupyter notebook --NotebookApp.ip="0.0.0.0" --no-browser --NotebookApp.token="" --NotebookApp.disable_check_xsrf=True --Application.log_level=10 --NotebookApp.allow_origin="*"
```

After that run script provided (because of the error it will hang, so you'll have to kill it):

```
from uuid import uuid4

from tornado import gen
from tornado.escape import json_encode, json_decode, url_escape
from tornado.httpclient import AsyncHTTPClient, HTTPRequest
from tornado.ioloop import IOLoop
from tornado.websocket import websocket_connect

BASE_URL = 'http://localhost:8254'
BASE_WS_URL = 'ws://localhost:8254'

SOURCE_CODE = 'disp(123)'


@gen.coroutine
def main():
    print(BASE_URL)
    print(BASE_WS_URL)

    client = AsyncHTTPClient()

    response = yield client.fetch(
        '{}/api/kernels'.format(BASE_URL),
        method='POST',
        auth_username='fakeuser',
        auth_password='fakepass',
        body=json_encode({'name': 'imatlab'})
    )
    kernel = json_decode(response.body)
    kernel_id = kernel['id']
    print('Created kernel {0}.'.format(kernel_id))

    ws_url  = '{}/api/kernels/{}/channels'.format(
        BASE_WS_URL,
        url_escape(kernel_id)
    )

    ws_req = HTTPRequest(
        url=ws_url,
        auth_username='fakeuser',
        auth_password='fakepass'
    )

    ws = yield websocket_connect(ws_req)
    print('Connected to kernel websocket')

    msg_id = uuid4().hex
    request = json_encode({
        'header': {
            'username': '',
            'version': '5.1',
            'session': '',
            'msg_id': msg_id,
            'msg_type': 'execute_request'
        },
        'parent_header': {},
        'channel': 'shell',
        'content': {
            'code': SOURCE_CODE,
            'silent': False,
            'store_history': False,
            'user_expressions': {},
            'allow_stdin': False
        },
        'metadata': {},
        'buffers': {}
    })
    print("SEND: {}".format(request))
    ws.write_message(request)

    while 1:
        msg = yield ws.read_message()
        msg = json_decode(msg)
        msg_type = msg['msg_type']
        print('RECEIVE: ', msg)

        if msg_type == 'error':
            print('ERROR')
            break

        if msg_type == 'stream':
            break

        if msg_type == 'execute_result':
            break

    msg_id = uuid4().hex
    request = json_encode({
        'header': {
            'username': '',
            'version': '5.1',
            'session': '',
            'msg_id': msg_id,
            'msg_type': 'shutdown_request'
        },
        'parent_header': {},
        'channel': 'shell',
        'content': {
            'restart': False
        },
        'metadata': {},
        'buffers': {}
    })
    print("SEND: {}".format(request))
    ws.write_message(request)

    while 1:
        msg = yield ws.read_message()
        msg = json_decode(msg)
        msg_type = msg['msg_type']
        print('RECEIVE: ', msg)

        if msg_type == 'error':
            print('ERROR')
            break

        if msg_type == 'shutdown_result':
            break


if __name__ == '__main__':
    try:
        IOLoop.current().run_sync(main)
    except Exception as ex:
        print(ex)
```

**Comment by anntzer** [comment]
I get a different error:
```
RECEIVE:  {'header': {'version': '5.2', 'date': '2017-11-20T07:32:04.508239Z', 'session': 'f44adad8-62d3753b05d84239d3fa90ff', 'username': 'antony', 'msg_type': 'stream', 'msg_id': 'e916677c-276d52fdc29b58d31fa6712e'}, 'msg_id': 'e916677c-276d52fdc29b58d31fa6712e', 'msg_type': 'stream', 'parent_header': {'username': '', 'version': '5.1', 'session': '', 'msg_id': '1e0583c11a09422fb883a2b5acd9ae40', 'msg_type': 'shutdown_request', 'date': '2017-11-20T07:32:02.926413Z'}, 'metadata': {}, 'content': {'name': 'stderr', 'text': '[IPKernelApp] ERROR | Exception in message handler:\nTraceback (most recent call last):\n  File "/usr/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell\n    handler(stream, idents, msg)\n  File "/usr/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 528, in shutdown_request\n    content = self.do_shutdown(parent[\'content\'][\'restart\'])\n  File "/home/antony/src/local/imatlab/lib/imatlab/_kernel.py", line 376, in do_shutdown\n    self._call("exit", nargout=0)\n  File "/home/antony/src/local/imatlab/lib/imatlab/_kernel.py", line 103, in _call\n    return self._engine.builtin(*args, **kwargs)\n  File "/usr/lib/python3.6/site-packages/matlab/engine/matlabengine.py", line 84, in __call__\n    _stderr, feval=True).result()\n  File "/usr/lib/python3.6/site-packages/matlab/engine/futureresult.py", line 68, in result\n    return self.__future.result(timeout)\n  File "/usr/lib/python3.6/site-packages/matlab/engine/fevalfuture.py", line 82, in result\n    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)\nmatlab.engine.EngineError: MATLAB function cannot be evaluated\n'}, 'buffers': [], 'channel': 'iopub'}
```
which suggests that you are running into a race condition (I guess somehow the kernel tries to call exit() after it has already shut down?).

I'm not sure I can fully protect against this (I mean, someone can always even shut down the kernel via a background thread), but would happily accept PRs to fix the issue (AFAICT this doesn't affect "regular" usage and I don't have a great idea of how to fix it)...
