### ISSUE TITLE
imatlab kernel quits right after started

### ISSUE THREAD

**Issue by CarlosEvo** [imatlab/imatlab#38]
Hi, I am on macOS 10.13, and the imatlab kernel throws an error and quits. Here is the debug log:

```
Traceback (most recent call last): File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main "main", mod_spec) File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code exec(code, run_globals) File "/usr/local/lib/python3.6/site-packages/imatlab/main.py", line 5, in IPKernelApp.launch_instance(kernel_class=MatlabKernel) File "/usr/local/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance app.initialize(argv) File "", line 2, in initialize File "/usr/local/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error return method(app, args, **kwargs) File "/usr/local/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 457, in initialize self.init_kernel() File "/usr/local/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 368, in init_kernel user_ns=self.user_ns, File "/usr/local/lib/python3.6/site-packages/traitlets/config/configurable.py", line 412, in instance inst = cls(args, **kwargs) File "/usr/local/lib/python3.6/site-packages/imatlab/_kernel.py", line 143, in init self._history = MatlabHistory(Path(self._call("prefdir"))) File "/usr/local/lib/python3.6/site-packages/imatlab/_kernel.py", line 47, in init self._et = ET.parse(str(prefdir / "History.xml")) File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse tree.parse(source, parser) File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/xml/etree/ElementTree.py", line 597, in parse self._root = parser._parse_whole(source) File "", line None xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 5509, column 113
```

Since I am running in Atom with Hydrogen, the error message is one-liner. Here is a screenshot for a better look: 
![image](https://user-images.githubusercontent.com/11689106/36513059-8680df3c-1722-11e8-97c9-583e5d71c1e2.png)

**Comment by anntzer** [comment]
Can you upload somewhere your History.xml file?  Should be somewhere like ~/.matlab/R20XXx/History.xml (not sure on OSX).

**Comment by CarlosEvo** [comment]
@anntzer actually I don't see anything related to Jupyter Kernel in my command history, but here is the history since I installed `imatlab`:

```xml
<session>
<command time_stamp="161bad76baa">%-- 2/21/18, 4:08 PM --%</command>
<command execution_time="33">matlabroot</command>
<command execution_time="68">stress</command>
<command batch="622" error="true">for gage_idx = 1: 10</command>
<command batch="622" error="true">strain_tmp.(sprintf('gage_%d', gage_idx)) = strain(:, 1 + gage_idx) .* 10^-6;</command>
<command batch="622" error="true" execution_time="35">end</command>
<command batch="623" error="true">for gage_idx = 1: 10</command>
<command batch="623" error="true">strain.(sprintf('gage_%d', gage_idx)) = strain(:, 1 + gage_idx) .* 10^-6;</command>
<command batch="623" error="true" execution_time="30">end</command>
<command execution_time="44">strain_tmp = dlmread('Arch_Data.dat');</command>
<command batch="624">for gage_idx = 1: 10</command>
<command batch="624">strain.(sprintf('gage_%d', gage_idx)) = strain_tmp(:, 1 + gage_idx) .* 10^-6;</command>
<command batch="624" execution_time="25">end</command>
<command batch="625">CONSTANT = struct(...</command>
<command batch="625">'SPAN', 200.3E-3, 'OD', 125E-3, 'ID', 105E-3,...</command>
<command batch="625">'GAGE_1', 0, 'GAGE_2', 15, 'GAGE_3', 30, 'GAGE_4', 45,...</command>
<command batch="625">'GAGE_8', 0, 'GAGE_7', 15, 'GAGE_6', 30, 'GAGE_5', 45 ...</command>
<command batch="625" execution_time="15">);</command>
<command execution_time="24">save('stress.mat')</command>
<command execution_time="159" repeat="5">stress</command>
<command execution_time="283">edit errorbar</command>
<command execution_time="39">a = [estm(1, 0), estm(2, 1)]</command>
<command execution_time="24">a(1).Value</command>
<command execution_time="19">a.Value</command>
<command execution_time="21">[a.Value]</command>
<command error="true" execution_time="156" repeat="4">stress</command>
<command execution_time="33">CONST.POS</command>
<command execution_time="45">[0: 15: 45, 45: 15: 15]</command>
<command execution_time="40">[0: 15: 45, 45: -15: 15]</command>
<command execution_time="201" repeat="2">stress</command>
<command execution_time="9266">edit(fullfile(matlabroot,'toolbox/local/TC.xml'))</command>
<command error="true" execution_time="69" repeat="2">stress</command>
<command execution_time="30">[strain.load(1: 4: end)]</command>
<command error="true" execution_time="611">stress</command>
<command execution_time="29">mkdir('figures')</command>
<command execution_time="2895" repeat="2">stress</command>
<command execution_time="29">[results_strain.(sprintf('gage_%d', gage_idx)).StandardError]</command>
</session>
```

**Comment by anntzer** [comment]
As the traceback above shows, something seems to be wrong in the history file at line 5509, column 113.  Can you check around that place?

**Comment by CarlosEvo** [comment]
@anntzer this is the line. Just realized that there is some weird characters... I deleted this line and the problem is fixed. I originally thought the line numbers meant somewhere in the code... Thank you so much!

```xml
<command execution_time="386">rmpath('/Users/CarlosZhang/Documents/MATLAB/Add-Ons/Functions/a-comparison-between-k-means-mean-shift-and-normalized-cut-segmentation')</command>
```

**Comment by anntzer** [comment]
If you open the normal matlab window and go back in the history, what was that line?  (i.e. what were the wrong characters?)  Can you upload that history file somewhere?
I'd like to at least know whether we could easily avoid the problem.

**Comment by CarlosEvo** [comment]
@anntzer unfortunately I think I lost the info of the character in copy and pasting...? But in python3
```python
ord(u'�')
```
gives 65533.

I don't know why does the character show up in my history.

**Comment by anntzer** [comment]
That's because your editor mangled it.  Can you eg zip the raw xml file and attach it to this discussion?

**Comment by CarlosEvo** [comment]
@anntzer I just managed to restore the file in time machine. See my edit above.

**Comment by anntzer** [comment]
Bah, too hard for me to figure out how that ended up there.  Will leave the issue as is unless you manage to reproduce how the character got introduced in the history file.

**Comment by CarlosEvo** [comment]
Alright, thanks for your help anyway!

**Comment by anntzer** [comment]
Indeed, looks like right now no History.xml gets generated if there is none to start with (https://github.com/imatlab/imatlab/blob/master/lib/imatlab/_kernel.py#L82 https://github.com/imatlab/imatlab/blob/master/lib/imatlab/_kernel.py#L86).  I think that was because I didn't want to bother about setting up the correct first few lines, encoding declaration etc.; in particular some tests had shown that MATLAB does not parse the encoding declaration by a general parser but something more brittle, so if you don't set it up correctly MATLAB will complain next time it tries to read History.xml.

Would be happy if you wanted to submit the PR to improve on that :-)
