### ISSUE TITLE
Engine Error Start on fresh install Anaconda 3.6 Windows 10 Matlab 2018b

### ISSUE THREAD

**Issue by linussun** [imatlab/imatlab#52]
Having difficulty with fresh install of anaconda in a 3.6 env on windows using conda git install of the lastest master branch, the kernel crashes and restarts giving the following message (repeating). 

[I 13:32:41.809 LabApp] KernelRestarter: restarting kernel (1/5), keep random ports
Error using import
Import argument 'matlab.internal.engine.input' cannot be found or cannot be imported.

Traceback (most recent call last):
  File "C:\Users\Psychophys\AppData\Local\conda\conda\envs\j36db\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Psychophys\AppData\Local\conda\conda\envs\j36db\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Psychophys\AppData\Local\conda\conda\envs\j36db\lib\site-packages\imatlab\__main__.py", line 5, in <module>
    IPKernelApp.launch_instance(kernel_class=MatlabKernel)
  File "C:\Users\Psychophys\AppData\Local\conda\conda\envs\j36db\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<C:\Users\Psychophys\AppData\Local\conda\conda\envs\j36db\lib\site-packages\decorator.py:decorator-gen-125>", line 2, in initialize
  File "C:\Users\Psychophys\AppData\Local\conda\conda\envs\j36db\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\Psychophys\AppData\Local\conda\conda\envs\j36db\lib\site-packages\ipykernel\kernelapp.py", line 484, in initialize
    self.init_kernel()
  File "C:\Users\Psychophys\AppData\Local\conda\conda\envs\j36db\lib\site-packages\ipykernel\kernelapp.py", line 389, in init_kernel
    user_ns=self.user_ns,
  File "C:\Users\Psychophys\AppData\Local\conda\conda\envs\j36db\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\Psychophys\AppData\Local\conda\conda\envs\j36db\lib\site-packages\imatlab\_kernel.py", line 163, in __init__
    self._engine = matlab.engine.start_matlab()
  File "C:\Users\Psychophys\AppData\Local\conda\conda\envs\j36db\lib\site-packages\matlab\engine\__init__.py", line 115, in start_matlab
    eng = future.result()
  File "C:\Users\Psychophys\AppData\Local\conda\conda\envs\j36db\lib\site-packages\matlab\engine\futureresult.py", line 67, in result
    return self.__future.result(timeout)
  File "C:\Users\Psychophys\AppData\Local\conda\conda\envs\j36db\lib\site-packages\matlab\engine\matlabfuture.py", line 87, in result
    handle = pythonengine.getMATLAB(self._future)
matlab.engine.EngineError: Import argument 'matlab.internal.engine.input' cannot be found or cannot be imported.
[I 13:32:46.796 LabApp] Interrupted...
[I 13:32:46.797 LabApp] Shutting down 1 kernel
[I 13:32:46.899 LabApp] Kernel shutdown: cfc171b0-0c31-403f-b5b4-cbb38b01abe1

**Comment by anntzer** [comment]
Can you start a matlab engine (`from matlab.engine import start_matlab; start_matlab()`) from a normal python prompt?  If not (which your traceback suggests), then the problem is with your install of the matlab engine for python.

**Comment by linussun** [comment]
It was a permissions issue with Windows 10. This doesn't happen with every installation, but if you run "jupyter lab" from the terminal you will get this unable to import matlab engine error. However if you run from an anaconda terminal (with administrator priviledge) everything works just fine. To get to this, you have to click on Windows 10 icon -> Anaconda 3 (64-bit) folder on my machine -> Right click anaconda prompt -> more -> run as administrator, then the engine appears to run without errors.  Not sure why my other installs worked just fine and this one requires the special admin terminal. I'll close for now as it is a permissions issue.
