### ISSUE TITLE
Nbconvert export to script fails due to exporter line in kernel

### ISSUE THREAD

**Issue by razimantv** [imatlab/imatlab#63]
I use `jupyter nbconvert --to script` to convert .ipynb files to .py, .m files etc. Should be able to do the same here with .m files. But when I try, I get errors like this

```
[NbConvertApp] Converting notebook Test/matlabtest.ipynb to script
Traceback (most recent call last):
  File "<virtualenv dir>/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "<virtualenv dir>/lib/python3.10/site-packages/jupyter_core/application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "<virtualenv dir>/lib/python3.10/site-packages/traitlets/config/application.py", line 978, in launch_instance
    app.start()
  File "<virtualenv dir>/lib/python3.10/site-packages/nbconvert/nbconvertapp.py", line 426, in start
    self.convert_notebooks()
  File "<virtualenv dir>/lib/python3.10/site-packages/nbconvert/nbconvertapp.py", line 600, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "<virtualenv dir>/lib/python3.10/site-packages/nbconvert/nbconvertapp.py", line 563, in convert_single_notebook
    output, resources = self.export_single_notebook(
  File "<virtualenv dir>/lib/python3.10/site-packages/nbconvert/nbconvertapp.py", line 491, in export_single_notebook
    output, resources = self.exporter.from_filename(
  File "<virtualenv dir>/lib/python3.10/site-packages/nbconvert/exporters/exporter.py", line 190, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "<virtualenv dir>/lib/python3.10/site-packages/nbconvert/exporters/exporter.py", line 207, in from_file
    return self.from_notebook_node(
  File "<virtualenv dir>/lib/python3.10/site-packages/nbconvert/exporters/script.py", line 60, in from_notebook_node
    return exporter.from_notebook_node(nb, resources, **kw)
  File "<virtualenv dir>/lib/python3.10/site-packages/nbconvert/exporters/templateexporter.py", line 402, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "<virtualenv dir>/lib/python3.10/site-packages/nbconvert/exporters/templateexporter.py", line 158, in template
    self._template_cached = self._load_template()
  File "<virtualenv dir>/lib/python3.10/site-packages/nbconvert/exporters/templateexporter.py", line 372, in _load_template
    return self.environment.get_template(template_file)
  File "<virtualenv dir>/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get
_template
    return self._load_template(name, globals)
  File "<virtualenv dir>/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "<virtualenv dir>/lib/python3.10/site-packages/jinja2/loaders.py", line 575, in load
    raise TemplateNotFound(name)
jinja2.exceptions.TemplateNotFound: matlab
```

But the error goes away if I remove this line in _kernel.py

https://github.com/imatlab/imatlab/blob/bbd657d77bfd06cb538f19ad4ad06ac5f413415d/lib/imatlab/_kernel.py#L155

**Comment by anntzer** [comment]
Sure, done.
