### ISSUE TITLE
matlabengineforpython (>=R2016b) is not a proper PEP440 requirement

### ISSUE THREAD

**Issue by bnavigator** [imatlab/imatlab#65]
This poses problems when parsing the package with packaging >= 22:

```
[   29s]   File "/usr/lib/python3.10/site-packages/packaging/requirements.py", line 35, in __init__
[   29s]     parsed = parse_requirement(requirement_string)
[   29s]   File "/usr/lib/python3.10/site-packages/packaging/_parser.py", line 64, in parse_requirement
[   29s]     return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
[   29s]   File "/usr/lib/python3.10/site-packages/packaging/_parser.py", line 82, in _parse_requirement
[   29s]     url, specifier, marker = _parse_requirement_details(tokenizer)
[   29s]   File "/usr/lib/python3.10/site-packages/packaging/_parser.py", line 116, in _parse_requirement_details
[   29s]     specifier = _parse_specifier(tokenizer)
[   29s]   File "/usr/lib/python3.10/site-packages/packaging/_parser.py", line 205, in _parse_specifier
[   29s]     parsed_specifiers = _parse_version_many(tokenizer)
[   29s]   File "/usr/lib/python3.10/site-packages/packaging/_parser.py", line 223, in _parse_version_many
[   29s]     version_token = tokenizer.expect("VERSION", expected="version after operator")
[   29s]   File "/usr/lib/python3.10/site-packages/packaging/_tokenizer.py", line 136, in expect
[   29s]     raise self.raise_syntax_error(f"Expected {expected}")
[   29s]   File "/usr/lib/python3.10/site-packages/packaging/_tokenizer.py", line 161, in raise_syntax_error
[   29s]     raise ParserSyntaxError(
[   29s] packaging._tokenizer.ParserSyntaxError: Expected version after operator
[   29s]     matlabengineforpython (>=R2016b)
[   29s]                              ^
[   29s] 
[   29s] The above exception was the direct cause of the following exception:
[   29s] 
[   29s] Traceback (most recent call last):
[   29s]   File "/usr/lib/rpm/pythondistdeps.py", line 561, in <module>
[   29s]     main()
[   29s]   File "/usr/lib/rpm/pythondistdeps.py", line 372, in main
[   29s]     dist = Distribution(f)
[   29s]   File "/usr/lib/rpm/pythondistdeps.py", line 86, in __init__
[   29s]     self.requirements = [Requirement(r) for r in self.requires or []]
[   29s]   File "/usr/lib/rpm/pythondistdeps.py", line 86, in <listcomp>
[   29s]     self.requirements = [Requirement(r) for r in self.requires or []]
[   29s]   File "/usr/lib/rpm/pythondistdeps.py", line 68, in __init__
[   29s]     super(Requirement, self).__init__(requirement_string)
[   29s]   File "/usr/lib/python3.10/site-packages/packaging/requirements.py", line 37, in __init__
[   29s]     raise InvalidRequirement(str(e)) from e
[   29s] packaging.requirements.InvalidRequirement: Expected version after operator
[   29s]     matlabengineforpython (>=R2016b)
[   29s]                              ^
[   29s] 
[   29s] The above exception was the direct cause of the following exception:
[   29s] 
[   29s] Traceback (most recent call last):
[   29s]   File "/usr/lib/rpm/pythondistdeps.py", line 564, in <module>
[   29s]     raise RuntimeError("Error: pythondistdeps.py generator encountered an unhandled exception and was terminated.") from exc
[   29s] RuntimeError: Error: pythondistdeps.py generator encountered an unhandled exception and was terminated.
```

Also note that for current R2022b the version is 9.13:

```
% pip install /opt/matlab/R2022b/extern/engines/python
Processing /opt/matlab/R2022b/extern/engines/python
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: matlabengineforpython
  Building wheel for matlabengineforpython (pyproject.toml) ... done
  Created wheel for matlabengineforpython: filename=matlabengineforpython-9.13-py3-none-any.whl size=16719 sha256=7c659fd449bc9528ebe9a27e9ca497fbab9d747e778923b6bcccc7ef39067aab
  Stored in directory: /tmp/pip-ephem-wheel-cache-gxnfvkim/wheels/34/7e/2e/13063070365bf553ba73e7ffb8ff597aec643123c55a9bad83
Successfully built matlabengineforpython
Installing collected packages: matlabengineforpython
Successfully installed matlabengineforpython-9.13
```

MathWorks even releases it on PyPI as matlabengine (!) and has it in a public GitHub repo;
- https://pypi.org/project/matlabengine 
- https://github.com/mathworks/matlab-engine-for-python

Ref: https://peps.python.org/pep-0440/

**Comment by anntzer** [comment]
Thanks for the report; now fixed.
